(cl:in-package core_communication_srvs-srv)
(cl:export '(CARTREACHINGACCURACYFLYBYPOINT-VAL
          CARTREACHINGACCURACYFLYBYPOINT
          ORIENTREACHINGACCURACYFLYBYPOINT-VAL
          ORIENTREACHINGACCURACYFLYBYPOINT
          CARTREACHINGACCURACYSTOPPOINT-VAL
          CARTREACHINGACCURACYSTOPPOINT
          ORIENTREACHINGACCURACYSTOPPOINT-VAL
          ORIENTREACHINGACCURACYSTOPPOINT
          JOINTREACHINGACCURACYSTOPPOINT-VAL
          JOINTREACHINGACCURACYSTOPPOINT
          DEFAULTENDEFFECTORVEL-VAL
          DEFAULTENDEFFECTORVEL
          DEFAULTJOINTVEL-VAL
          DEFAULTJOINTVEL
))