(cl:in-package core_communication_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          TRAJECTORYEXECUTIONSTATE-VAL
          TRAJECTORYEXECUTIONSTATE
          TRAJECTORYEXECUTIONSTATESTRING-VAL
          TRAJECTORYEXECUTIONSTATESTRING
          EXECUTED_TRAJECTORY_POINT_INDEX-VAL
          EXECUTED_TRAJECTORY_POINT_INDEX
          TRAJECTORY_EXECUTION_TIME-VAL
          TRAJECTORY_EXECUTION_TIME
          IS_TRAJECTORY_TO_START_POINT-VAL
          IS_TRAJECTORY_TO_START_POINT
))