(cl:in-package core_communication_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          GRAVITY_VECTOR_TORQUE-VAL
          GRAVITY_VECTOR_TORQUE
          CORIOLIS_VECTOR_TORQUE-VAL
          CORIOLIS_VECTOR_TORQUE
          MASS_MATRIX_MULT_WITH_ACC_TORQUE-VAL
          MASS_MATRIX_MULT_WITH_ACC_TORQUE
          INVERSE_DYNAMICS_TORQUE-VAL
          INVERSE_DYNAMICS_TORQUE
          DIRECT_DYNAMICS_ACC-VAL
          DIRECT_DYNAMICS_ACC
))