(cl:in-package core_communication_msgs-msg)
(cl:export '(TRAJECTORYPOINT-VAL
          TRAJECTORYPOINT
          GRIPPERACTION-VAL
          GRIPPERACTION
          REACHINGACCURACYCART-VAL
          REACHINGACCURACYCART
          REACHINGACCURACYORIENT-VAL
          REACHINGACCURACYORIENT
          REACHINGACCURACYJOINT-VAL
          REACHINGACCURACYJOINT
          CONTROLLOOPRATIO-VAL
          CONTROLLOOPRATIO
))