(cl:in-package core_communication_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          CONTROL_SIGNAL_VOLTAGES-VAL
          CONTROL_SIGNAL_VOLTAGES
          CONTROL_SIGNAL_TORQUES-VAL
          CONTROL_SIGNAL_TORQUES
          JOINT_POSITION_ERROR-VAL
          JOINT_POSITION_ERROR
          JOINT_VELOCITY_ERROR-VAL
          JOINT_VELOCITY_ERROR
          CARTESIAN_POSITION_ERROR-VAL
          CARTESIAN_POSITION_ERROR
          CARTESIAN_ORIENTATION_ERROR-VAL
          CARTESIAN_ORIENTATION_ERROR
          CARTESIAN_POSITION_ERROR_NEXT_WAY_POINT-VAL
          CARTESIAN_POSITION_ERROR_NEXT_WAY_POINT
          CARTESIAN_ORIENTATION_ERROR_NEXT_WAY_POINT-VAL
          CARTESIAN_ORIENTATION_ERROR_NEXT_WAY_POINT
          ERRORS-VAL
          ERRORS
))