/* Auto-generated by genmsg_cpp for file /home/biorob/rosstacks/core_dev/core_communication_msgs/msg/BioRobExecutionState.msg */
#ifndef CORE_COMMUNICATION_MSGS_MESSAGE_BIOROBEXECUTIONSTATE_H
#define CORE_COMMUNICATION_MSGS_MESSAGE_BIOROBEXECUTIONSTATE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace core_communication_msgs
{
template <class ContainerAllocator>
struct BioRobExecutionState_ {
  typedef BioRobExecutionState_<ContainerAllocator> Type;

  BioRobExecutionState_()
  : header()
  , connected(false)
  , enabled(false)
  , executionState(0)
  , executionStateString()
  , initialized(false)
  {
  }

  BioRobExecutionState_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , connected(false)
  , enabled(false)
  , executionState(0)
  , executionStateString(_alloc)
  , initialized(false)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef uint8_t _connected_type;
  uint8_t connected;

  typedef uint8_t _enabled_type;
  uint8_t enabled;

  typedef uint32_t _executionState_type;
  uint32_t executionState;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _executionStateString_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  executionStateString;

  typedef uint8_t _initialized_type;
  uint8_t initialized;


  typedef boost::shared_ptr< ::core_communication_msgs::BioRobExecutionState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::core_communication_msgs::BioRobExecutionState_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct BioRobExecutionState
typedef  ::core_communication_msgs::BioRobExecutionState_<std::allocator<void> > BioRobExecutionState;

typedef boost::shared_ptr< ::core_communication_msgs::BioRobExecutionState> BioRobExecutionStatePtr;
typedef boost::shared_ptr< ::core_communication_msgs::BioRobExecutionState const> BioRobExecutionStateConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::core_communication_msgs::BioRobExecutionState_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::core_communication_msgs::BioRobExecutionState_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace core_communication_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::core_communication_msgs::BioRobExecutionState_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::core_communication_msgs::BioRobExecutionState_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::core_communication_msgs::BioRobExecutionState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "5ec225b9018e1847deb260c173b02645";
  }

  static const char* value(const  ::core_communication_msgs::BioRobExecutionState_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x5ec225b9018e1847ULL;
  static const uint64_t static_value2 = 0xdeb260c173b02645ULL;
};

template<class ContainerAllocator>
struct DataType< ::core_communication_msgs::BioRobExecutionState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "core_communication_msgs/BioRobExecutionState";
  }

  static const char* value(const  ::core_communication_msgs::BioRobExecutionState_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::core_communication_msgs::BioRobExecutionState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
bool connected\n\
bool enabled\n\
uint32 executionState\n\
string executionStateString\n\
bool initialized\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::core_communication_msgs::BioRobExecutionState_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::core_communication_msgs::BioRobExecutionState_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::core_communication_msgs::BioRobExecutionState_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::core_communication_msgs::BioRobExecutionState_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.connected);
    stream.next(m.enabled);
    stream.next(m.executionState);
    stream.next(m.executionStateString);
    stream.next(m.initialized);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct BioRobExecutionState_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::core_communication_msgs::BioRobExecutionState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::core_communication_msgs::BioRobExecutionState_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "connected: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.connected);
    s << indent << "enabled: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enabled);
    s << indent << "executionState: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.executionState);
    s << indent << "executionStateString: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.executionStateString);
    s << indent << "initialized: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.initialized);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CORE_COMMUNICATION_MSGS_MESSAGE_BIOROBEXECUTIONSTATE_H

