/* Auto-generated by genmsg_cpp for file /home/biorob/rosstacks/core_dev/core_communication_msgs/msg/BioRobTrajectoryExecutionState.msg */
#ifndef CORE_COMMUNICATION_MSGS_MESSAGE_BIOROBTRAJECTORYEXECUTIONSTATE_H
#define CORE_COMMUNICATION_MSGS_MESSAGE_BIOROBTRAJECTORYEXECUTIONSTATE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace core_communication_msgs
{
template <class ContainerAllocator>
struct BioRobTrajectoryExecutionState_ {
  typedef BioRobTrajectoryExecutionState_<ContainerAllocator> Type;

  BioRobTrajectoryExecutionState_()
  : header()
  , trajectoryExecutionState(0)
  , trajectoryExecutionStateString()
  , executed_trajectory_point_index(0)
  , trajectory_execution_time(0.0)
  , is_trajectory_to_start_point(false)
  {
  }

  BioRobTrajectoryExecutionState_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , trajectoryExecutionState(0)
  , trajectoryExecutionStateString(_alloc)
  , executed_trajectory_point_index(0)
  , trajectory_execution_time(0.0)
  , is_trajectory_to_start_point(false)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef uint32_t _trajectoryExecutionState_type;
  uint32_t trajectoryExecutionState;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _trajectoryExecutionStateString_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  trajectoryExecutionStateString;

  typedef uint32_t _executed_trajectory_point_index_type;
  uint32_t executed_trajectory_point_index;

  typedef double _trajectory_execution_time_type;
  double trajectory_execution_time;

  typedef uint8_t _is_trajectory_to_start_point_type;
  uint8_t is_trajectory_to_start_point;


  typedef boost::shared_ptr< ::core_communication_msgs::BioRobTrajectoryExecutionState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::core_communication_msgs::BioRobTrajectoryExecutionState_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct BioRobTrajectoryExecutionState
typedef  ::core_communication_msgs::BioRobTrajectoryExecutionState_<std::allocator<void> > BioRobTrajectoryExecutionState;

typedef boost::shared_ptr< ::core_communication_msgs::BioRobTrajectoryExecutionState> BioRobTrajectoryExecutionStatePtr;
typedef boost::shared_ptr< ::core_communication_msgs::BioRobTrajectoryExecutionState const> BioRobTrajectoryExecutionStateConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::core_communication_msgs::BioRobTrajectoryExecutionState_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::core_communication_msgs::BioRobTrajectoryExecutionState_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace core_communication_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::core_communication_msgs::BioRobTrajectoryExecutionState_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::core_communication_msgs::BioRobTrajectoryExecutionState_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::core_communication_msgs::BioRobTrajectoryExecutionState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "63d24642823c1f3b74ad7b1e16a105fb";
  }

  static const char* value(const  ::core_communication_msgs::BioRobTrajectoryExecutionState_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x63d24642823c1f3bULL;
  static const uint64_t static_value2 = 0x74ad7b1e16a105fbULL;
};

template<class ContainerAllocator>
struct DataType< ::core_communication_msgs::BioRobTrajectoryExecutionState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "core_communication_msgs/BioRobTrajectoryExecutionState";
  }

  static const char* value(const  ::core_communication_msgs::BioRobTrajectoryExecutionState_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::core_communication_msgs::BioRobTrajectoryExecutionState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
uint32 trajectoryExecutionState\n\
string trajectoryExecutionStateString\n\
uint32 executed_trajectory_point_index\n\
float64 trajectory_execution_time\n\
bool is_trajectory_to_start_point\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::core_communication_msgs::BioRobTrajectoryExecutionState_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::core_communication_msgs::BioRobTrajectoryExecutionState_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::core_communication_msgs::BioRobTrajectoryExecutionState_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::core_communication_msgs::BioRobTrajectoryExecutionState_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.trajectoryExecutionState);
    stream.next(m.trajectoryExecutionStateString);
    stream.next(m.executed_trajectory_point_index);
    stream.next(m.trajectory_execution_time);
    stream.next(m.is_trajectory_to_start_point);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct BioRobTrajectoryExecutionState_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::core_communication_msgs::BioRobTrajectoryExecutionState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::core_communication_msgs::BioRobTrajectoryExecutionState_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "trajectoryExecutionState: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.trajectoryExecutionState);
    s << indent << "trajectoryExecutionStateString: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.trajectoryExecutionStateString);
    s << indent << "executed_trajectory_point_index: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.executed_trajectory_point_index);
    s << indent << "trajectory_execution_time: ";
    Printer<double>::stream(s, indent + "  ", v.trajectory_execution_time);
    s << indent << "is_trajectory_to_start_point: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_trajectory_to_start_point);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CORE_COMMUNICATION_MSGS_MESSAGE_BIOROBTRAJECTORYEXECUTIONSTATE_H

