/* Auto-generated by genmsg_cpp for file /home/biorob/rosstacks/core_dev/core_communication_msgs/msg/DigitalSignal.msg */
#ifndef CORE_COMMUNICATION_MSGS_MESSAGE_DIGITALSIGNAL_H
#define CORE_COMMUNICATION_MSGS_MESSAGE_DIGITALSIGNAL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace core_communication_msgs
{
template <class ContainerAllocator>
struct DigitalSignal_ {
  typedef DigitalSignal_<ContainerAllocator> Type;

  DigitalSignal_()
  : name()
  , state(false)
  {
  }

  DigitalSignal_(const ContainerAllocator& _alloc)
  : name(_alloc)
  , state(false)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  name;

  typedef uint8_t _state_type;
  uint8_t state;


  typedef boost::shared_ptr< ::core_communication_msgs::DigitalSignal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::core_communication_msgs::DigitalSignal_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct DigitalSignal
typedef  ::core_communication_msgs::DigitalSignal_<std::allocator<void> > DigitalSignal;

typedef boost::shared_ptr< ::core_communication_msgs::DigitalSignal> DigitalSignalPtr;
typedef boost::shared_ptr< ::core_communication_msgs::DigitalSignal const> DigitalSignalConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::core_communication_msgs::DigitalSignal_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::core_communication_msgs::DigitalSignal_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace core_communication_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::core_communication_msgs::DigitalSignal_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::core_communication_msgs::DigitalSignal_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::core_communication_msgs::DigitalSignal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "a02bbd4704518df654c6d45037dfc59f";
  }

  static const char* value(const  ::core_communication_msgs::DigitalSignal_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xa02bbd4704518df6ULL;
  static const uint64_t static_value2 = 0x54c6d45037dfc59fULL;
};

template<class ContainerAllocator>
struct DataType< ::core_communication_msgs::DigitalSignal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "core_communication_msgs/DigitalSignal";
  }

  static const char* value(const  ::core_communication_msgs::DigitalSignal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::core_communication_msgs::DigitalSignal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "string name\n\
bool state\n\
\n\
";
  }

  static const char* value(const  ::core_communication_msgs::DigitalSignal_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::core_communication_msgs::DigitalSignal_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.name);
    stream.next(m.state);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct DigitalSignal_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::core_communication_msgs::DigitalSignal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::core_communication_msgs::DigitalSignal_<ContainerAllocator> & v) 
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CORE_COMMUNICATION_MSGS_MESSAGE_DIGITALSIGNAL_H

