/* Auto-generated by genmsg_cpp for file /home/biorob/rosstacks/core_dev/core_communication_msgs/msg/GripperState.msg */
#ifndef CORE_COMMUNICATION_MSGS_MESSAGE_GRIPPERSTATE_H
#define CORE_COMMUNICATION_MSGS_MESSAGE_GRIPPERSTATE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace core_communication_msgs
{
template <class ContainerAllocator>
struct GripperState_ {
  typedef GripperState_<ContainerAllocator> Type;

  GripperState_()
  : header()
  , opening(0.0)
  , theta(0.0)
  , q(0.0)
  , current(0.0)
  , voltage(0.0)
  {
  }

  GripperState_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , opening(0.0)
  , theta(0.0)
  , q(0.0)
  , current(0.0)
  , voltage(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef double _opening_type;
  double opening;

  typedef double _theta_type;
  double theta;

  typedef double _q_type;
  double q;

  typedef double _current_type;
  double current;

  typedef double _voltage_type;
  double voltage;


  typedef boost::shared_ptr< ::core_communication_msgs::GripperState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::core_communication_msgs::GripperState_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct GripperState
typedef  ::core_communication_msgs::GripperState_<std::allocator<void> > GripperState;

typedef boost::shared_ptr< ::core_communication_msgs::GripperState> GripperStatePtr;
typedef boost::shared_ptr< ::core_communication_msgs::GripperState const> GripperStateConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::core_communication_msgs::GripperState_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::core_communication_msgs::GripperState_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace core_communication_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::core_communication_msgs::GripperState_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::core_communication_msgs::GripperState_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::core_communication_msgs::GripperState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "a86aa4cbada2bcfb9e0c0e4431ddd519";
  }

  static const char* value(const  ::core_communication_msgs::GripperState_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xa86aa4cbada2bcfbULL;
  static const uint64_t static_value2 = 0x9e0c0e4431ddd519ULL;
};

template<class ContainerAllocator>
struct DataType< ::core_communication_msgs::GripperState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "core_communication_msgs/GripperState";
  }

  static const char* value(const  ::core_communication_msgs::GripperState_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::core_communication_msgs::GripperState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
float64 opening\n\
float64 theta\n\
float64 q\n\
float64 current\n\
float64 voltage\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::core_communication_msgs::GripperState_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::core_communication_msgs::GripperState_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::core_communication_msgs::GripperState_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::core_communication_msgs::GripperState_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.opening);
    stream.next(m.theta);
    stream.next(m.q);
    stream.next(m.current);
    stream.next(m.voltage);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GripperState_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::core_communication_msgs::GripperState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::core_communication_msgs::GripperState_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "opening: ";
    Printer<double>::stream(s, indent + "  ", v.opening);
    s << indent << "theta: ";
    Printer<double>::stream(s, indent + "  ", v.theta);
    s << indent << "q: ";
    Printer<double>::stream(s, indent + "  ", v.q);
    s << indent << "current: ";
    Printer<double>::stream(s, indent + "  ", v.current);
    s << indent << "voltage: ";
    Printer<double>::stream(s, indent + "  ", v.voltage);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CORE_COMMUNICATION_MSGS_MESSAGE_GRIPPERSTATE_H

