# request fields
---
# response fields
float64 cartReachingAccuracyFlyByPoint
float64 orientReachingAccuracyFlyByPoint
float64 cartReachingAccuracyStopPoint
float64 orientReachingAccuracyStopPoint
float64 jointReachingAccuracyStopPoint
float64 defaultEndeffectorVel
float64 defaultJointVel
