"""autogenerated by genpy from core_communication_msgs/BioRobTrajectoryExecutionState.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class BioRobTrajectoryExecutionState(genpy.Message):
  _md5sum = "63d24642823c1f3b74ad7b1e16a105fb"
  _type = "core_communication_msgs/BioRobTrajectoryExecutionState"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header
uint32 trajectoryExecutionState
string trajectoryExecutionStateString
uint32 executed_trajectory_point_index
float64 trajectory_execution_time
bool is_trajectory_to_start_point

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

"""
  __slots__ = ['header','trajectoryExecutionState','trajectoryExecutionStateString','executed_trajectory_point_index','trajectory_execution_time','is_trajectory_to_start_point']
  _slot_types = ['std_msgs/Header','uint32','string','uint32','float64','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,trajectoryExecutionState,trajectoryExecutionStateString,executed_trajectory_point_index,trajectory_execution_time,is_trajectory_to_start_point

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(BioRobTrajectoryExecutionState, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.trajectoryExecutionState is None:
        self.trajectoryExecutionState = 0
      if self.trajectoryExecutionStateString is None:
        self.trajectoryExecutionStateString = ''
      if self.executed_trajectory_point_index is None:
        self.executed_trajectory_point_index = 0
      if self.trajectory_execution_time is None:
        self.trajectory_execution_time = 0.
      if self.is_trajectory_to_start_point is None:
        self.is_trajectory_to_start_point = False
    else:
      self.header = std_msgs.msg.Header()
      self.trajectoryExecutionState = 0
      self.trajectoryExecutionStateString = ''
      self.executed_trajectory_point_index = 0
      self.trajectory_execution_time = 0.
      self.is_trajectory_to_start_point = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_struct_I.pack(self.trajectoryExecutionState))
      _x = self.trajectoryExecutionStateString
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_IdB.pack(_x.executed_trajectory_point_index, _x.trajectory_execution_time, _x.is_trajectory_to_start_point))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (self.trajectoryExecutionState,) = _struct_I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.trajectoryExecutionStateString = str[start:end].decode('utf-8')
      else:
        self.trajectoryExecutionStateString = str[start:end]
      _x = self
      start = end
      end += 13
      (_x.executed_trajectory_point_index, _x.trajectory_execution_time, _x.is_trajectory_to_start_point,) = _struct_IdB.unpack(str[start:end])
      self.is_trajectory_to_start_point = bool(self.is_trajectory_to_start_point)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_struct_I.pack(self.trajectoryExecutionState))
      _x = self.trajectoryExecutionStateString
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_IdB.pack(_x.executed_trajectory_point_index, _x.trajectory_execution_time, _x.is_trajectory_to_start_point))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (self.trajectoryExecutionState,) = _struct_I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.trajectoryExecutionStateString = str[start:end].decode('utf-8')
      else:
        self.trajectoryExecutionStateString = str[start:end]
      _x = self
      start = end
      end += 13
      (_x.executed_trajectory_point_index, _x.trajectory_execution_time, _x.is_trajectory_to_start_point,) = _struct_IdB.unpack(str[start:end])
      self.is_trajectory_to_start_point = bool(self.is_trajectory_to_start_point)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3I = struct.Struct("<3I")
_struct_IdB = struct.Struct("<IdB")
