"""autogenerated by genpy from core_communication_msgs/GripperAction.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class GripperAction(genpy.Message):
  _md5sum = "67688fdf428828504144a527b96201ec"
  _type = "core_communication_msgs/GripperAction"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64 absolutePosition
bool absPosIsSet
bool closeGripper
float64 noMovementTimeout
bool openGripper
bool useCustomNoMovementTimeout

"""
  __slots__ = ['absolutePosition','absPosIsSet','closeGripper','noMovementTimeout','openGripper','useCustomNoMovementTimeout']
  _slot_types = ['float64','bool','bool','float64','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       absolutePosition,absPosIsSet,closeGripper,noMovementTimeout,openGripper,useCustomNoMovementTimeout

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GripperAction, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.absolutePosition is None:
        self.absolutePosition = 0.
      if self.absPosIsSet is None:
        self.absPosIsSet = False
      if self.closeGripper is None:
        self.closeGripper = False
      if self.noMovementTimeout is None:
        self.noMovementTimeout = 0.
      if self.openGripper is None:
        self.openGripper = False
      if self.useCustomNoMovementTimeout is None:
        self.useCustomNoMovementTimeout = False
    else:
      self.absolutePosition = 0.
      self.absPosIsSet = False
      self.closeGripper = False
      self.noMovementTimeout = 0.
      self.openGripper = False
      self.useCustomNoMovementTimeout = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_d2Bd2B.pack(_x.absolutePosition, _x.absPosIsSet, _x.closeGripper, _x.noMovementTimeout, _x.openGripper, _x.useCustomNoMovementTimeout))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.absolutePosition, _x.absPosIsSet, _x.closeGripper, _x.noMovementTimeout, _x.openGripper, _x.useCustomNoMovementTimeout,) = _struct_d2Bd2B.unpack(str[start:end])
      self.absPosIsSet = bool(self.absPosIsSet)
      self.closeGripper = bool(self.closeGripper)
      self.openGripper = bool(self.openGripper)
      self.useCustomNoMovementTimeout = bool(self.useCustomNoMovementTimeout)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_d2Bd2B.pack(_x.absolutePosition, _x.absPosIsSet, _x.closeGripper, _x.noMovementTimeout, _x.openGripper, _x.useCustomNoMovementTimeout))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.absolutePosition, _x.absPosIsSet, _x.closeGripper, _x.noMovementTimeout, _x.openGripper, _x.useCustomNoMovementTimeout,) = _struct_d2Bd2B.unpack(str[start:end])
      self.absPosIsSet = bool(self.absPosIsSet)
      self.closeGripper = bool(self.closeGripper)
      self.openGripper = bool(self.openGripper)
      self.useCustomNoMovementTimeout = bool(self.useCustomNoMovementTimeout)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_d2Bd2B = struct.Struct("<d2Bd2B")
