"""autogenerated by genpy from core_communication_msgs/ProcessExecutionState.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ProcessExecutionState(genpy.Message):
  _md5sum = "062eedcbddf675783ad1802e7ee31590"
  _type = "core_communication_msgs/ProcessExecutionState"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool process_paused
bool process_running
bool process_finished

"""
  __slots__ = ['process_paused','process_running','process_finished']
  _slot_types = ['bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       process_paused,process_running,process_finished

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ProcessExecutionState, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.process_paused is None:
        self.process_paused = False
      if self.process_running is None:
        self.process_running = False
      if self.process_finished is None:
        self.process_finished = False
    else:
      self.process_paused = False
      self.process_running = False
      self.process_finished = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3B.pack(_x.process_paused, _x.process_running, _x.process_finished))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 3
      (_x.process_paused, _x.process_running, _x.process_finished,) = _struct_3B.unpack(str[start:end])
      self.process_paused = bool(self.process_paused)
      self.process_running = bool(self.process_running)
      self.process_finished = bool(self.process_finished)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3B.pack(_x.process_paused, _x.process_running, _x.process_finished))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 3
      (_x.process_paused, _x.process_running, _x.process_finished,) = _struct_3B.unpack(str[start:end])
      self.process_paused = bool(self.process_paused)
      self.process_running = bool(self.process_running)
      self.process_finished = bool(self.process_finished)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3B = struct.Struct("<3B")
