"""autogenerated by genpy from core_communication_msgs/robotInitialization.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class robotInitialization(genpy.Message):
  _md5sum = "4d3ae86cafc174b346dfc3efe19b7eb6"
  _type = "core_communication_msgs/robotInitialization"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool connectDisconnectRobot
bool enableDisableRobot
bool resetMotorEncoder
bool value

"""
  __slots__ = ['connectDisconnectRobot','enableDisableRobot','resetMotorEncoder','value']
  _slot_types = ['bool','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       connectDisconnectRobot,enableDisableRobot,resetMotorEncoder,value

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(robotInitialization, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.connectDisconnectRobot is None:
        self.connectDisconnectRobot = False
      if self.enableDisableRobot is None:
        self.enableDisableRobot = False
      if self.resetMotorEncoder is None:
        self.resetMotorEncoder = False
      if self.value is None:
        self.value = False
    else:
      self.connectDisconnectRobot = False
      self.enableDisableRobot = False
      self.resetMotorEncoder = False
      self.value = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_4B.pack(_x.connectDisconnectRobot, _x.enableDisableRobot, _x.resetMotorEncoder, _x.value))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 4
      (_x.connectDisconnectRobot, _x.enableDisableRobot, _x.resetMotorEncoder, _x.value,) = _struct_4B.unpack(str[start:end])
      self.connectDisconnectRobot = bool(self.connectDisconnectRobot)
      self.enableDisableRobot = bool(self.enableDisableRobot)
      self.resetMotorEncoder = bool(self.resetMotorEncoder)
      self.value = bool(self.value)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_4B.pack(_x.connectDisconnectRobot, _x.enableDisableRobot, _x.resetMotorEncoder, _x.value))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 4
      (_x.connectDisconnectRobot, _x.enableDisableRobot, _x.resetMotorEncoder, _x.value,) = _struct_4B.unpack(str[start:end])
      self.connectDisconnectRobot = bool(self.connectDisconnectRobot)
      self.enableDisableRobot = bool(self.enableDisableRobot)
      self.resetMotorEncoder = bool(self.resetMotorEncoder)
      self.value = bool(self.value)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_4B = struct.Struct("<4B")
